// 序卦傳/雜卦傳 per-hexagram snippets — generated by scripts/generate-sequence.ts
// from data-acquisition/xugua-zagua.json (classical, public domain) and
// legge-cleaned.json (Legge English, public domain). Do not edit by hand.

/** Sequence (序卦傳) and paired epigram (雜卦傳) texts for one hexagram */
export interface SequenceTexts {
  xu: string; // 序卦傳 — why this hexagram follows the previous (classical only; Legge's xu is paragraph-segmented, not per-hexagram)
  za: string; // 雜卦傳 — the terse paired epigram (shared by the 綜 pair)
  zaEn: string; // Legge English couplet (pair-aligned)
}

/** 64 entries, indexed by King Wen number - 1 */
export const SEQUENCE: SequenceTexts[] = [
  {
    xu: "有天地，然後萬物生焉。",
    za: "《乾》剛《坤》柔。",
    zaEn: "Strength in Khien, weakness in Khwan we find.",
  },
  {
    xu: "有天地，然後萬物生焉。",
    za: "《乾》剛《坤》柔。",
    zaEn: "Strength in Khien, weakness in Khwan we find.",
  },
  {
    xu: "盈天地之間者唯萬物，故受之以《屯》。",
    za: "《屯》見而不失其居。",
    zaEn: "Kun manifests itself, yet keeps its place",
  },
  {
    xu: "《屯》者，盈也。屯者，物之始生也。物生必蒙，故受之以《蒙》。",
    za: "《蒙》雜而著。",
    zaEn: "'Mid darkness still, to light Mang sets its face.",
  },
  {
    xu: "《蒙》者，蒙也，物之稺也。物稺不可不養也，故受之以《需》。",
    za: "《需》，不進也。",
    zaEn: "Hsu shows its subject making no advance:",
  },
  {
    xu: "《需》者，飲食之道也。飲食必有訟，故受之以《訟》。",
    za: "《訟》，不親也。",
    zaEn: "In Sung we seek in vain a friendly glance",
  },
  {
    xu: "訟必有眾起，故受之以《師》。",
    za: "《比》樂《師》憂。",
    zaEn: "Pi shows us joy, and Sze the anxious mind.",
  },
  {
    xu: "《師》者，眾也。眾必有所比，故受之以《比》。",
    za: "《比》樂《師》憂。",
    zaEn: "Pi shows us joy, and Sze the anxious mind.",
  },
  {
    xu: "《比》者，比也。比必有所畜，故受之以《小畜》。",
    za: "《小畜》，寡也。",
    zaEn: "Hsiao Khu with few 'gainst many foes contends.",
  },
  {
    xu: "物畜然後有禮，故受之以《履》。",
    za: "《履》，不處也。",
    zaEn: "Movement in Li, unresting, never ends.",
  },
  {
    xu: "履而泰然後安，故受之以《泰》。",
    za: "《否》《泰》，反其類也。",
    zaEn: "While Phi and Thai their different scopes prefer,",
  },
  {
    xu: "《泰》者，通也。物不可以終通，故受之以《否》。",
    za: "《否》《泰》，反其類也。",
    zaEn: "While Phi and Thai their different scopes prefer,",
  },
  {
    xu: "物不可以終否，故受之以《同人》。",
    za: "《同人》，親也。",
    zaEn: "Thung Zan reflects their warm affection's glow.",
  },
  {
    xu: "與人同者，物必歸焉，故受之以《大有》。",
    za: "《大有》，眾也。",
    zaEn: "Ta Yu adhering multitudes can show",
  },
  {
    xu: "有大者不可以盈，故受之以《謙》。",
    za: "《謙》輕而《豫》怠也。",
    zaEn: "Khien itself, Yu others doth despise.",
  },
  {
    xu: "有大而能謙必豫，故受之以《豫》。",
    za: "《謙》輕而《豫》怠也。",
    zaEn: "Khien itself, Yu others doth despise.",
  },
  {
    xu: "豫必有隨，故受之以《隨》。",
    za: "《隨》，无故也。",
    zaEn: "Sui quits the old; Ku makes a new decree.",
  },
  {
    xu: "以喜隨人者必有事，故受之以《蠱》。",
    za: "《蠱》則飭也。",
    zaEn: "Sui quits the old; Ku makes a new decree.",
  },
  {
    xu: "《蠱》者，事也。有事而後可大，故受之以《臨》。",
    za: "《臨》《觀》之義，或與或求。",
    zaEn: "Lin gives, Kwan seeks;—such are the several themes Their different figures were to teach designed.",
  },
  {
    xu: "《臨》者，大也。物大然後可觀，故受之以《觀》。",
    za: "《臨》《觀》之義，或與或求。",
    zaEn: "Lin gives, Kwan seeks;—such are the several themes Their different figures were to teach designed.",
  },
  {
    xu: "可觀而後有所合，故受之以《噬嗑》。",
    za: "《噬嗑》，食也。",
    zaEn: "Shih Ho takes eating for its theme; and Pi Takes what is plain, from ornament quite free.",
  },
  {
    xu: "嗑者，合也。物不可以苟合而已，故受之以《賁》。",
    za: "《賁》，无色也。",
    zaEn: "Shih Ho takes eating for its theme; and Pi Takes what is plain, from ornament quite free.",
  },
  {
    xu: "《賁》者，飾也。致飾然後亨則盡矣，故受之以《剝》。",
    za: "《剝》，爛也。",
    zaEn: "We see in Po its subject worn away",
  },
  {
    xu: "《剝》者，剝也。物不可以終盡剝，窮上反下，故受之以《復》。",
    za: "《復》，反也。",
    zaEn: "And Fu shows its recovering from decay.",
  },
  {
    xu: "復則不妄矣，故受之以《无妄》。",
    za: "《无妄》，災也。",
    zaEn: "Wu Wang sets forth how evil springs from crime.",
  },
  {
    xu: "有无妄，然後可畜，故受之以《大畜》。",
    za: "《大畜》，時也。",
    zaEn: "Ta Khu keeps still, and waits the proper time.",
  },
  {
    xu: "物畜然後可養，故受之以《頤》。",
    za: "《頤》，養正也。",
    zaEn: "Body and mind are nourished right in I",
  },
  {
    xu: "《頤》者，養也。不養則不可動，故受之以《大過》。",
    za: "《大過》，顛也。",
    zaEn: "And Ta Kwo's overthrown with sad mischance.",
  },
  {
    xu: "物不可以終過，故受之以《坎》。",
    za: "《離》上而《坎》下也。",
    zaEn: "Fire mounts in Li; water in Khan descends.",
  },
  {
    xu: "《坎》者，陷也。陷必有所麗，故受之以《離》。《離》者，麗也。",
    za: "《離》上而《坎》下也。",
    zaEn: "Fire mounts in Li; water in Khan descends.",
  },
  {
    xu: "有天地然後有萬物，有萬物然後有男女，有男女然後有夫婦，有夫婦然後有父子，有父子然後有君臣，有君臣然後有上下，有上下然後禮義有所錯。",
    za: "《咸》，速也。",
    zaEn: "Effect quick answering cause in Hsien appears",
  },
  {
    xu: "夫婦之道不可以不久也，故受之以《恆》。",
    za: "《恆》，久也。",
    zaEn: "While Hang denotes continuance for years.",
  },
  {
    xu: "《恆》者，久也。物不可以久居其所，故受之以《遯》。",
    za: "《大壯》則止，《遯》則退也。",
    zaEn: "Ta Kwang stops here as right; withdraws Thun there.",
  },
  {
    xu: "《遯》者，退也。物不可以終遯，故受之以《大壯》。",
    za: "《大壯》則止，《遯》則退也。",
    zaEn: "Ta Kwang stops here as right; withdraws Thun there.",
  },
  {
    xu: "物不可以終壯，故受之以《晉》。",
    za: "《晉》，晝也。",
    zaEn: "Above in Zin the sun shines clear and bright",
  },
  {
    xu: "《晉》者，進也。進必有所傷，故受之以《明夷》。",
    za: "《明夷》，誅也。",
    zaEn: "But in Ming I 'tis hidden from the sight.",
  },
  {
    xu: "夷者，傷也。傷於外者必反於家，故受之以《家人》。",
    za: "《家人》，內也。",
    zaEn: "Kia Zan all includes within its sphere.",
  },
  {
    xu: "家道窮必乖，故受之以《睽》。",
    za: "《睽》，外也。",
    zaEn: "Khwei looks on others as beyond its care",
  },
  {
    xu: "《睽》者，乖也。乖必有難，故受之以《蹇》。",
    za: "《蹇》，難也。",
    zaEn: "Hard toil and danger have in Kien their home.",
  },
  {
    xu: "《蹇》者，難也。物不可以終難，故受之以《解》。",
    za: "《解》，緩也。",
    zaEn: "Relief and ease with Kieh are sure to come",
  },
  {
    xu: "《解》者，緩也。緩必有所失，故受之以《損》。",
    za: "《損》《益》，盛衰之始也。",
    zaEn: "In Sun and Yi are seen How fulness and decay their course begin.",
  },
  {
    xu: "損而不已必益，故受之以《益》。",
    za: "《損》《益》，盛衰之始也。",
    zaEn: "In Sun and Yi are seen How fulness and decay their course begin.",
  },
  {
    xu: "益而不已必決，故受之以《夬》。",
    za: "《夬》，決也，剛決柔也。",
    zaEn: "The strong disperse the weak; Kwai teaches so. Prospers the good man's way; to grief all small men go.",
  },
  {
    xu: "《夬》者，決也。決必有遇，故受之以《姤》。",
    za: "《姤》，遇也，柔遇剛也。",
    zaEn: "Kau shows a meeting, where the many strong Are met by one that's weak, yet struggles long.",
  },
  {
    xu: "《姤》者，遇也。物相遇而後聚，故受之以《萃》。",
    za: "《萃》聚而《升》不來也。",
    zaEn: "Good men in Zhui collect; in Shang they rise:",
  },
  {
    xu: "《萃》者，聚也。聚而上者謂之升，故受之以《升》。",
    za: "《萃》聚而《升》不來也。",
    zaEn: "Good men in Zhui collect; in Shang they rise:",
  },
  {
    xu: "升而不已必困，故受之以《困》。",
    za: "《井》通而《困》相遇也。",
    zaEn: "Progress in Zing in Khwan encounters blight.",
  },
  {
    xu: "困乎上者必反下，故受之以《井》。",
    za: "《井》通而《困》相遇也。",
    zaEn: "Progress in Zing in Khwan encounters blight.",
  },
  {
    xu: "井道不可不革，故受之以《革》。",
    za: "《革》，去故也。",
    zaEn: "Ting takes what's new; the old is left by Ko.",
  },
  {
    xu: "革物者莫若鼎，故受之以《鼎》。",
    za: "《鼎》，取新也。",
    zaEn: "Ting takes what's new; the old is left by Ko.",
  },
  {
    xu: "主器者莫若長子，故受之以《震》。",
    za: "《震》，起也。《艮》，止也。",
    zaEn: "Kan starts; Kan stops.",
  },
  {
    xu: "《震》者，動也。物不可以終動，止之，故受之以《艮》。",
    za: "《震》，起也。《艮》，止也。",
    zaEn: "Kan starts; Kan stops.",
  },
  {
    xu: "《艮》者，止也。物不可以終止，故受之以《漸》。",
    za: "《漸》，女歸待男行也。",
    zaEn: "In Kien we see a bride who will delay To move until the bridegroom takes his way.",
  },
  {
    xu: "漸者，進也。進必有所歸，故受之以《歸妹》。",
    za: "《歸妹》，女之終也。",
    zaEn: "Kwei Mei reveals how ends the virgin life",
  },
  {
    xu: "得其所歸者必大，故受之以《豐》。",
    za: "《豐》，多故也。",
    zaEn: "Fang tells of trouble; Lu can boast few friends.",
  },
  {
    xu: "《豐》者，大也。窮大者必失其居，故受之以《旅》。",
    za: "親寡《旅》也。",
    zaEn: "Fang tells of trouble; Lu can boast few friends.",
  },
  {
    xu: "旅而无所容，故受之以《巽》。",
    za: "《兌》見而《巽》伏也。",
    zaEn: "Tui shows its scope, but Sun's we do not see.",
  },
  {
    xu: "《巽》者，入也。入而後說之，故受之以《兌》。",
    za: "《兌》見而《巽》伏也。",
    zaEn: "Tui shows its scope, but Sun's we do not see.",
  },
  {
    xu: "《兌》者，說也。說而後散之，故受之以《渙》。",
    za: "《渙》，離也。",
    zaEn: "Hwan scatters; but Zieh its code of rules uprears.",
  },
  {
    xu: "《渙》者，離也。物不可以終離，故受之以《節》。",
    za: "《節》，止也。",
    zaEn: "Hwan scatters; but Zieh its code of rules uprears.",
  },
  {
    xu: "節而信之，故受之以《中孚》。",
    za: "《中孚》，信也。",
    zaEn: "Sincere is Kung Fu; but exceeds, Hsiao Kwo.",
  },
  {
    xu: "有其信者必行之，故受之以《小過》。",
    za: "《小過》，過也。",
    zaEn: "Sincere is Kung Fu; but exceeds, Hsiao Kwo.",
  },
  {
    xu: "有過物者必濟，故受之以《既濟》。",
    za: "《既濟》，定也。",
    zaEn: "All things are well established in Ki Zi.",
  },
  {
    xu: "物不可窮也，故受之以《未濟》，終焉。",
    za: "《未濟》，男之窮也。",
    zaEn: "Wei Zi how fails the youth (to get a wife).",
  },
];
