#!/usr/bin/env bun
/**
 * One-off generator: packages/core/src/data/sequence.ts — per-hexagram
 * 序卦傳/雜卦傳 snippets.
 *
 *   xu         序卦傳 — why this hexagram follows the previous one
 *              (classical, from data-acquisition/xugua-zagua.json xuGua).
 *              No English: legge-cleaned wings.xuGua is segmented by
 *              paragraph, not per hexagram (n=3..5 share one passage), so a
 *              per-hexagram English text would misattribute neighbors.
 *   za / zaEn  雜卦傳 — the terse paired epigram (classical zaGua entries are
 *              keyed by 綜 pair; each hexagram receives its pair's line;
 *              English couplets from legge-cleaned wings.zaGua, pair-aligned)
 *
 * The data-acquisition/ directory is gitignored; pass its path as argv[2]
 * if running from elsewhere:
 *
 *   bun scripts/generate-sequence.ts [path/to/data-acquisition]
 *
 * Kept in scripts/ for provenance of the generated module.
 */

import { join } from "path";

interface WingEntry {
  hexagram: number;
  text: string;
}

interface PairEntry {
  pair: number[];
  text: string;
}

const dataDir = process.argv[2] ?? join(import.meta.dir, "..", "data-acquisition");
const outPath = join(import.meta.dir, "..", "packages", "core", "src", "data", "sequence.ts");

const wings = (await Bun.file(join(dataDir, "xugua-zagua.json")).json()) as {
  xuGua: WingEntry[];
  zaGua: PairEntry[];
};
const legge = (await Bun.file(join(dataDir, "legge-cleaned.json")).json()) as {
  wings: { xuGua: { n: number; text: string }[]; zaGua: PairEntry[] };
};

/**
 * legge-cleaned.json wings.zaGua carries two mis-tagged pairs (verified
 * against the classical text):
 *   - "Hard toil and danger have in Kien their home."  → Kien is 蹇 (39),
 *     not 41 (Sun, already covered by the [41,42] couplet);
 *   - "Ting takes what's new; the old is left by Ko."  → Ko is 革 (49),
 *     not 51 (Kan, covered by its own couplet). 革去故也，鼎取新也.
 */
function fixLeggePair(e: PairEntry): number[] {
  if (e.text.includes("in Kien their home")) return [39];
  if (e.text.includes("left by Ko")) return [50, 49];
  return e.pair ?? [];
}

function zaFor(
  n: number,
  entries: PairEntry[],
  label: string,
  pairOf: (e: PairEntry) => number[] = (e) => e.pair ?? [],
): string {
  const entry = entries.find((e) => pairOf(e).includes(n));
  if (!entry) throw new Error(`${label}: no 雜卦 entry covers hexagram ${n}`);
  return entry.text;
}

const rows: string[] = [];
for (let n = 1; n <= 64; n++) {
  const xu = wings.xuGua.find((e) => e.hexagram === n);
  if (!xu) throw new Error(`missing 序卦 for hexagram ${n}`);
  const za = zaFor(n, wings.zaGua, "classical");
  const zaEn = zaFor(n, legge.wings.zaGua, "legge", fixLeggePair);
  rows.push(
    [
      "  {",
      `    xu: ${JSON.stringify(xu.text)},`,
      `    za: ${JSON.stringify(za)},`,
      `    zaEn: ${JSON.stringify(zaEn)},`,
      "  },",
    ].join("\n"),
  );
}

const out = `// 序卦傳/雜卦傳 per-hexagram snippets — generated by scripts/generate-sequence.ts
// from data-acquisition/xugua-zagua.json (classical, public domain) and
// legge-cleaned.json (Legge English, public domain). Do not edit by hand.

/** Sequence (序卦傳) and paired epigram (雜卦傳) texts for one hexagram */
export interface SequenceTexts {
  xu: string; // 序卦傳 — why this hexagram follows the previous (classical only; Legge's xu is paragraph-segmented, not per-hexagram)
  za: string; // 雜卦傳 — the terse paired epigram (shared by the 綜 pair)
  zaEn: string; // Legge English couplet (pair-aligned)
}

/** 64 entries, indexed by King Wen number - 1 */
export const SEQUENCE: SequenceTexts[] = [
${rows.join("\n")}
];
`;

await Bun.write(outPath, out);
console.log(`Wrote 64 sequence entries → ${outPath}`);
