#!/usr/bin/env bun
/**
 * Pre-render all 64 hexagram Chinese names as braille terminal art.
 * 3 fonts × 3 sizes × 64 characters = 576 renders.
 * Output: packages/core/src/data/large-glyphs.ts
 *
 * Each glyph is stored as an array of row strings (braille characters),
 * enabling row-by-row scanline animation, fade-in, and progressive reveal.
 */

import { spawnSync } from "child_process";
import { GUA } from "../packages/core/src/data/gua.ts";

// ── Fonts ──

const FONTS: Record<string, { path: string; index: number }> = {
  kaiti: {
    path: "/System/Library/AssetsV2/com_apple_MobileAsset_Font8/88d6cc32a907955efa1d014207889413890573be.asset/AssetData/Kaiti.ttc",
    index: 0,
  },
  libian: {
    path: "/System/Library/AssetsV2/com_apple_MobileAsset_Font8/a304e3396d019087ab67af77f5e398977529007d.asset/AssetData/Libian.ttc",
    index: 0,
  },
  heiti: {
    path: "/System/Library/Fonts/STHeiti Medium.ttc",
    index: 0,
  },
};

const SIZES = [32, 48, 64];

// ── Renderer ──

function renderToBrailleRows(
  char: string,
  w: number,
  h: number,
  fontPath: string,
  fontIndex: number,
): string[] | null {
  const py = `
import sys
from PIL import Image, ImageDraw, ImageFont

char, w, h = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])
font_path, font_index = sys.argv[4], int(sys.argv[5])
font_size = min(w, h) - 6

try:
    font = ImageFont.truetype(font_path, font_size, index=font_index)
except:
    sys.exit(1)

img = Image.new('L', (w, h), 0)
draw = ImageDraw.Draw(img)
bbox = draw.textbbox((0, 0), char, font=font)
tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
x = (w - tw) // 2 - bbox[0]
y = (h - th) // 2 - bbox[1]
draw.text((x, y), char, fill=255, font=font)

for row in range(h):
    line = ''
    for col in range(w):
        line += '1' if img.getpixel((col, row)) > 60 else '0'
    print(line)
`;

  const r = spawnSync("python3", ["-c", py, char, String(w), String(h), fontPath, String(fontIndex)], {
    encoding: "utf-8",
    timeout: 5000,
  });

  if (r.status !== 0) return null;

  const bitmap = r.stdout.trim().split("\n").map(l => [...l].map(c => c === "1"));
  const rows = bitmap.length;
  const cols = bitmap[0]?.length ?? 0;
  const brailleRows: string[] = [];

  for (let y = 0; y < rows; y += 4) {
    let line = "";
    for (let x = 0; x < cols; x += 2) {
      let code = 0x2800;
      const dots: [number, number, number][] = [
        [0, 0, 1], [1, 0, 2], [2, 0, 4], [3, 0, 64],
        [0, 1, 8], [1, 1, 16], [2, 1, 32], [3, 1, 128],
      ];
      for (const [dy, dx, bit] of dots) {
        const py = y + dy;
        const px = x + dx;
        if (py < rows && px < cols && bitmap[py][px]) {
          code |= bit;
        }
      }
      line += String.fromCharCode(code);
    }
    brailleRows.push(line);
  }

  // Trim empty rows from top and bottom
  let start = 0;
  while (start < brailleRows.length && brailleRows[start].replace(/⠀/g, "").length === 0) start++;
  let end = brailleRows.length - 1;
  while (end > start && brailleRows[end].replace(/⠀/g, "").length === 0) end--;

  return brailleRows.slice(start, end + 1);
}

// ── Generate ──

type GlyphData = Record<string, Record<string, Record<number, string[]>>>;

const data: GlyphData = {};
let total = 0;
let failed = 0;

console.log(`Generating braille glyphs for ${GUA.length} hexagrams × ${Object.keys(FONTS).length} fonts × ${SIZES.length} sizes...\n`);

for (let i = 0; i < GUA.length; i++) {
  const gua = GUA[i];
  const char = gua.n;
  const kw = i + 1;

  // Handle multi-char names (e.g., 小畜, 大有, 噬嗑)
  // For multi-char, render first char only for the large glyph
  const renderChar = char.length > 1 ? char[0] : char;

  data[char] = {};

  for (const [fontName, fontConfig] of Object.entries(FONTS)) {
    data[char][fontName] = {};

    for (const size of SIZES) {
      const rows = renderToBrailleRows(renderChar, size, size, fontConfig.path, fontConfig.index);
      if (rows) {
        data[char][fontName][size] = rows;
        total++;
      } else {
        failed++;
        process.stderr.write(`  FAIL: ${char} ${fontName} ${size}\n`);
      }
    }
  }

  // Progress
  if ((i + 1) % 8 === 0) {
    process.stdout.write(`  ${i + 1}/${GUA.length} hexagrams rendered\n`);
  }
}

console.log(`\nDone: ${total} glyphs rendered, ${failed} failed.\n`);

// ── Output as TypeScript ──

const outputPath = "packages/core/src/data/large-glyphs.ts";

let ts = `// Auto-generated by scripts/generate-glyphs.ts
// ${total} glyphs: ${GUA.length} hexagrams × ${Object.keys(FONTS).length} fonts × ${SIZES.length} sizes
// Each glyph is an array of braille row strings for scanline animation.
//
// Fonts: kaiti (楷体), libian (隶变), heiti (黑体)
// Sizes: ${SIZES.join(", ")} (bitmap pixels → braille rows)

export type GlyphFont = "kaiti" | "libian" | "heiti";
export type GlyphSize = ${SIZES.join(" | ")};

export interface GlyphEntry {
  rows: string[];
  width: number;  // braille columns per row
  height: number; // number of rows
}

/** Lookup: LARGE_GLYPHS[chineseName][font][size] → GlyphEntry */
export const LARGE_GLYPHS: Record<string, Record<GlyphFont, Record<GlyphSize, GlyphEntry>>> = {\n`;

for (const [char, fonts] of Object.entries(data)) {
  ts += `  ${JSON.stringify(char)}: {\n`;
  for (const [fontName, sizes] of Object.entries(fonts)) {
    ts += `    ${fontName}: {\n`;
    for (const [size, rows] of Object.entries(sizes)) {
      const rowStrs = rows as string[];
      const width = rowStrs[0]?.length ?? 0;
      const height = rowStrs.length;
      ts += `      ${size}: { width: ${width}, height: ${height}, rows: [\n`;
      for (const row of rowStrs) {
        ts += `        ${JSON.stringify(row)},\n`;
      }
      ts += `      ] },\n`;
    }
    ts += `    },\n`;
  }
  ts += `  },\n`;
}

ts += `};\n`;

await Bun.write(outputPath, ts);
console.log(`Written to ${outputPath}`);
console.log(`File size: ${(new TextEncoder().encode(ts).length / 1024).toFixed(1)} KB`);
